#!/usr/bin/env bash

LOCK_FILE="$HOME/.cache/eww-calendar.lock"
EWW_CONFIG_DIR="$HOME/.config/eww"

run() {
  eww -c "$EWW_CONFIG_DIR" open calendar
}

if [[ ! -f "$LOCK_FILE" ]]; then
  touch "$LOCK_FILE"
  run
else
  eww -c "$EWW_CONFIG_DIR" close calendar
  rm "$LOCK_FILE"
fi
