#!/usr/bin/env bash

VOLUME=$(pamixer --get-volume)
IS_MUTED=$(pamixer --get-mute)

if [[ "$1" == "--percent" ]]; then
  echo "$VOLUME"
elif [[ "$1" == "--icon" ]]; then
  if [[ $IS_MUTED == "true" ]]; then
      echo -n "󰖁"
  else
    case $VOLUME in
      7[0-9]|8[0-9]|9[0-9]|1[0-9][0-9])
          echo ""
        ;;
      4[0-9]|5[0-9]|6[0-9])
          echo "󰕾"
        ;;
      1[0-9]|2[0-9]|3[0-9])
          echo "󰖀"
        ;;
      [1-9])
          echo ""
        ;;
      *)
          echo "󰖁"
        ;;
    esac
  fi
fi
