#!/bin/bash
export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

# Down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi

ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down

# Set the theme.toml config
leftwm-command "LoadTheme $SCRIPTPATH/theme.toml"

polybar -c "$SCRIPTPATH"/polybar.config mainbar-leftwm &> /dev/null

