#! /bin/sh

# ----| Init |----
sxhkd &
$HOME/.config/polybar/launch.sh &
wmname LG3D &

# ----| Display |----
bspc monitor -d I II III IV V VI VII VIII IX 

# ----| Config |----
# bspc config pointer_modifier mod1

bspc config border_width          2
bspc config window_gap            10

bspc config split_ratio           0.5
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config single_monocle        true
bspc config focus_follows_pointer true

bspc config normal_border_color		      "#008df8"
bspc config active_border_color	          "#00d8eb"
bspc config focused_border_color	      "#8ce10b"
bspc config presel_feedback_color	      "#ffb900"
bspc config urgent_border_color 	      "#ff000f"

# ----| Rule |----

# -- remove all rules firts
bspc rule -r *:*

# ----| Desktops |----
bspc desktop ^1  -l monocle
bspc desktop ^2  -l monocle
bspc desktop ^3  -l monocle
bspc desktop ^4  -l monocle
bspc desktop ^5  -l monocle
bspc desktop ^6  -l monocle
bspc desktop ^7  -l monocle
bspc desktop ^8  -l monocle
bspc desktop ^9  -l monocle

# ----| 1 |----
bspc rule -a firefox desktop='^1'
bspc rule -a firefoxdeveloperedition desktop='^1'
# ----| 2 |----
# bspc rule -a Alacritty desktop='^2' focus=off
# ----| 3 |----
# ----| 4 |----
# ----| 5 |----
bspc rule -a Thunar desktop='^5'
bspc rule -a PCmanFM desktop='^5'
# ----| 6 |----
bspc rule -a stacer desktop='^6'
# ----| 7 |----
bspc rule -a Inkscape desktop='^7'
# ----| 8 |----
bspc rule -a TelegramDesktop desktop='^8'
bspc rule -a WhatsappDesktop desktop='^8'
bspc rule -a Thunderbird desktop='^8'
bspc rule -a discord desktop='^8'
bspc rule -a Webex desktop='^8'
# ----| 9 |----
bspc rule -a Spotify desktop='^9'

# ----| Pseudo Titled |----

# ----| Floating |----
bspc rule -a wpa_gui state=floating center=true
bspc rule -a SpeedCrunch state=floating center=true
bspc rule -a Nitrogen state=floating center=true
bspc rule -a Lxappearance state=floating center=true
bspc rule -a firefox:Places state=floating follow=on focus=on
bspc rule -a firefox:Dialog state=floating follow=on focus=on
bspc rule -a firefoxdeveloperedition:Places state=floating follow=on focus=on
bspc rule -a firefoxdeveloperedition:Dialog state=floating follow=on focus=on
bspc rule -a Thunar:Dialog state=floating center=true
bspc rule -a Zathura state=floating follow=on center=true

# ----| |----
bscp rule -a polybar manage=off
