#!/bin/python

import os
import re

monitor: str = "HDMI1"
laptop: str = "eDP1"

window_gap: float = 10
top_padding: float = 10
boot_padding: float = 10
right_padding: float = 10
left_padding: float = 10

border_width: float = 2

split_ratio: float = 0.5
borderless_monocle: bool = True
gapless_monocle: bool = True
single_margin: bool = True
focus_follows_pointer: bool = True

colors = {
    "cyan": "#00acc1",
    "blue": "#00d8eb",
    "green": "#43a047",
    "yellow": "#ffb300",
    "red": "#e53935"
}

# ----| Init |----
inits: list[str] = [
    "sxhkd &",
    "wmname LG3D &",
    #"$HOME/.config/polybar/launch.sh &"
]

for init in inits:
    os.system(init)

# ----| Display |----
my_laptop_external_monitor: str = os.system(f"xrandr --query | grep {monitor}")
regex_connected = r"/^connected/"
if re.match(regex_connected, my_laptop_external_monitor):
    os.system("bspc monitor $MONITOR -d I II III IV V")
    os.system("bspc monitor $LAPTOP -d VI VII VIII IX X")
else:
    os.system("bspc monitor $LAPTOP -d I II III IV V VI VII VIII IX X")

# # ----| Config |----
os.system(f"bspc config border_width {border_width}")

workspaces: list[str] = os.system("bspc query -D")

for workspace in workspaces:
    os.system(f"bspc config -d {workspace} window_gap {window_gap}")
    os.system(f"bspc config -d {workspace} top_padding {top_padding}")
    os.system(f"bspc config -d {workspace} bottom_padding {bottom_padding}")
    os.system(f"bspc config -d {workspace} left_padding {left_padding}")
    os.system(f"bspc config -d {workspace} right_padding {right_padding}")

os.system(f"bspc config split_ratio {split_ratio}")
os.system(f"bspc config borderless_monocle {borderless_monocle}")
os.system(f"bspc config gapless_monocle {gapless_monocle}")
os.system(f"bspc config signed_monocle {signed_monocle}")
os.system(f"bspc config focus_follows_pointer {focus_follows_pointer}")

os.system(f"bspc config normal_border_color {colors.cyan}")
os.system(f"bspc config active_border_color {colors.blue}")
os.system(f"bspc config focused_border_color {colors.green}")
os.system(f"bspc config presel_feedback_color {colors.yellow}")
os.system(f"bspc config urgent_border_color {colors.red}")

# ----| Rule |----
# -- remove all rules firts
os.system("bspc rule -r *:*")

# ----| Desktops |----
os.system("bspc desktop ^1 -l monocle")
os.system("bspc desktop ^2 -l monocle")
os.system("bspc desktop ^3 -l monocle")
os.system("bspc desktop ^4 -l monocle")
os.system("bspc desktop ^5 -l monocle")
os.system("bspc desktop ^6 -l monocle")
os.system("bspc desktop ^7 -l monocle")
os.system("bspc desktop ^8 -l monocle")
os.system("bspc desktop ^9 -l monocle")
os.system("bspc desktop ^0 -l monocle")

# ----| |----
os.system("bspc rule -a polybar manage=off")

# # ----| 1 |----
# bspc rule -a Brave-browser desktop='^1'
# bspc rule -a Brave-browser-beta desktop='^1'
# bspc rule -a firefox-aurora desktop='^1'Implemented the methods and added the callbacks
# # ----| 2 |----
# # bspc rule -a Alacritty desktop='^2' focus=off
# # ----| 3 |----
# # ----| 4 |----
# bspc rule -a firefox desktop='^4'
# bspc rule -a Google-chrome desktop='^4'
# # ----| 5 |----
# bspc rule -a Thunar desktop='^5'
# bspc rule -a pcmanfm desktop='^5'
# # ----| 6 |----
# bspc rule -a stacer desktop='^6'
# bspc rule -a DBeaver desktop='^6'
# # ----| 7 |----
# bspc rule -a Inkscape desktop='^7'
# bspc rule -a zoom desktop='^7' focus=off state=floating
# # ----| 8 |----
# bspc rule -a Thunderbird desktop='^8' focus=off follow=off
# bspc rule -a discord desktop='^8' focus=off follow=off
# bspc rule -a Webex desktop='^8' focus=off follow=off
# bspc rule -a Zoom desktop='^8' focus=off follow=off
# bspc rule -a ClickUp desktop='^8' focus=off follow=off
# # ----| 9 |----
# bspc rule -a spotify desktop='^9'
# bspc rule -a Pavucontrol desktop='^9'
# bspc rule -a Pulseaudio-equalizer-gtk desktop='^9'
# # ----| 10 |----
# bspc rule -a Slack desktop='^10' focus=off follow=off
#
# # ----| Pseudo Titled |----
#
# # ----| Floating |----
# bspc rule -a wpa_gui state=floating center=true
# bspc rule -a SpeedCrunch state=floating center=true
# bspc rule -a Nitrogen state=floating center=true
# bspc rule -a Lxappearance state=floating center=true
# bspc rule -a firefox:Places state=floating follow=on focus=on
# bspc rule -a firefox:Dialog state=floating follow=on focus=on
# bspc rule -a Brave-browser:Places state=floating follow=on focus=on
# bspc rule -a Brave-browser:pop-up state=floating follow=on focus=on
# bspc rule -a Brave-browser-beta:Places state=floating follow=on focus=on
# bspc rule -a Brave-browser-beta:pop-up state=floating follow=on focus=on
# bspc rule -a Google-chrome:Places state=floating follow=on focus=on
# bspc rule -a Google-chrome:pop-up state=floating follow=on focus=on
# bspc rule -a firefox-aurora:Places state=floating follow=on focus=on
# bspc rule -a firefox-aurora:Dialog state=floating follow=on focus=on
# bspc rule -a firefox-aurora:Toolkit state=floating follow=on focus=on
# bspc rule -a Thunar:Dialog state=floating center=true
# bspc rule -a Zathura state=floating follow=on center=true
# bspc rule -a Pavucontrol state=floating follow=on center=true
# bspc rule -a Pulseaudio-equalizer-gtk state=floating follow=on center=true
# bspc rule -a Blueman-manager state=floating follow=on center=true
# bspc rule -a Piper state=floating follow=on center=true
# bspc rule -a NordPass state=floating follow=on center=true
# bspc rule -a Arandr state=floating follow=on center=true
# bspc rule -a Postman state=floating follow=on center=true
# bspc rule -a Java state=floating follow=on center=true
# bspc rule -a TelegramDesktop state=floating follow=on center=true
# bspc rule -a whatsapp-nativefier-d40211 state=floating follow=on center=true
